In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file_path = "../data/raw_data/EduPro Online Platform.xlsx"

In [3]:
cleaned_file_path = "../data/cleaned_data/EduPro Online Platform Cleaned.xlsx"

In [4]:
excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['Users', 'Teachers', 'Courses', 'Transactions']

In [5]:
users = pd.read_excel(file_path, sheet_name="Users")
teachers = pd.read_excel(file_path, sheet_name="Teachers")
courses = pd.read_excel(file_path, sheet_name="Courses")
transactions = pd.read_excel(file_path, sheet_name="Transactions")

## Making Copies

In [6]:
users_clean = users.copy()
teachers_clean = teachers.copy()
courses_clean = courses.copy()
transactions_clean = transactions.copy()

In [7]:
print("Original Users:", users.shape)
print("Clean Users:", users_clean.shape)

print("Original Teachers:", teachers.shape)
print("Clean Teachers:", teachers_clean.shape)

print("Original Courses:", courses.shape)
print("Clean Courses:", courses_clean.shape)

print("Original Transactions:", transactions.shape)
print("Clean Transactions:", transactions_clean.shape)

Original Users: (3000, 5)
Clean Users: (3000, 5)
Original Teachers: (60, 7)
Clean Teachers: (60, 7)
Original Courses: (60, 8)
Clean Courses: (60, 8)
Original Transactions: (10000, 7)
Clean Transactions: (10000, 7)

## Missing Value Check

In [8]:
print("Users Missing Values")
print(users_clean.isnull().sum().sum())

print("\nTeachers Missing Values")
print(teachers_clean.isnull().sum().sum())

print("\nCourses Missing Values")
print(courses_clean.isnull().sum().sum())

print("\nTransactions Missing Values")
print(transactions_clean.isnull().sum().sum())

Users Missing Values
0

Teachers Missing Values
0

Courses Missing Values
0

Transactions Missing Values
0

## Checking Duplicate Values

In [9]:
print("Duplicate Users:", users_clean.duplicated().sum())
print("Duplicate Teachers:", teachers_clean.duplicated().sum())
print("Duplicate Courses:", courses_clean.duplicated().sum())
print("Duplicate Transactions:", transactions_clean.duplicated().sum())

Duplicate Users: 0
Duplicate Teachers: 0
Duplicate Courses: 0
Duplicate Transactions: 0

In [10]:
users_clean[users_clean.duplicated()]

Empty DataFrame
Columns: [UserID, UserName, Age, Gender, Email]
Index: []

In [11]:
teachers_clean[teachers_clean.duplicated()]

Empty DataFrame
Columns: [TeacherID, TeacherName, Age, Gender, Expertise, YearsOfExperience, TeacherRating]
Index: []

In [12]:
courses_clean[courses_clean.duplicated()]

Empty DataFrame
Columns: [CourseID, CourseName, CourseCategory, CourseType, CourseLevel, CoursePrice, CourseDuration, CourseRating]
Index: []

In [13]:
transactions_clean[transactions_clean.duplicated()]

Empty DataFrame
Columns: [TransactionID, UserID, CourseID, TransactionDate, Amount, PaymentMethod, TeacherID]
Index: []

## Checking Duplicate IDs

In [14]:
print("Duplicate User IDs:",
      users_clean["UserID"].duplicated().sum())

print("Duplicate Teacher IDs:",
      teachers_clean["TeacherID"].duplicated().sum())

print("Duplicate Course IDs:",
      courses_clean["CourseID"].duplicated().sum())

print("Duplicate Transaction IDs:",
      transactions_clean["TransactionID"].duplicated().sum())

Duplicate User IDs: 0
Duplicate Teacher IDs: 0
Duplicate Course IDs: 0
Duplicate Transaction IDs: 0

In [15]:
print(users_clean["UserID"].nunique())
print(teachers_clean["TeacherID"].nunique())
print(courses_clean["CourseID"].nunique())
print(transactions_clean["TransactionID"].nunique())

3000
60
60
10000

## Clean Text Fields

In [16]:
text_columns_users = ["UserID", "UserName", "Gender", "Email"]

for col in text_columns_users:
    users_clean[col] = users_clean[col].str.strip()

In [17]:
text_columns_teachers = [
    "TeacherID",
    "TeacherName",
    "Gender",
    "Expertise"
]

for col in text_columns_teachers:
    teachers_clean[col] = teachers_clean[col].str.strip()

In [18]:
text_columns_courses = [
    "CourseID",
    "CourseName",
    "CourseCategory",
    "CourseType",
    "CourseLevel"
]

for col in text_columns_courses:
    courses_clean[col] = courses_clean[col].str.strip()

In [19]:
text_columns_transactions = [
    "TransactionID",
    "UserID",
    "CourseID",
    "PaymentMethod",
    "TeacherID"
]

for col in text_columns_transactions:
    transactions_clean[col] = transactions_clean[col].str.strip()

In [20]:
courses_clean["CourseType"].value_counts()

CourseType
Free    38
Paid    22
Name: count, dtype: int64

In [21]:
courses_clean["CourseLevel"].value_counts()

CourseLevel
Beginner        21
Advanced        21
Intermediate    18
Name: count, dtype: int64

## Validate Gender

In [22]:
print("Users",users_clean["Gender"].value_counts())
print("Teachers",teachers_clean["Gender"].value_counts())

Users Gender
Female    1520
Male      1480
Name: count, dtype: int64
Teachers Gender
Male      33
Female    27
Name: count, dtype: int64

## Validate numeric columns

### Users

In [23]:
users_clean["Age"].describe()

count    3000.000000
mean       24.974333
std         6.046475
min        15.000000
25%        20.000000
50%        25.000000
75%        30.000000
max        35.000000
Name: Age, dtype: float64

In [24]:
users_clean[
    (users_clean["Age"] < 0) |
    (users_clean["Age"] > 100)
]

Empty DataFrame
Columns: [UserID, UserName, Age, Gender, Email]
Index: []

### Teachers

In [25]:
teachers_clean["Age"].describe()

count    60.000000
mean     38.450000
std       7.703015
min      27.000000
25%      32.000000
50%      36.500000
75%      46.250000
max      50.000000
Name: Age, dtype: float64

In [26]:
teachers_clean["YearsOfExperience"].describe()

count    60.000000
mean      6.283333
std       4.715972
min       1.000000
25%       3.000000
50%       6.000000
75%       8.000000
max      24.000000
Name: YearsOfExperience, dtype: float64

In [27]:
teachers_clean["TeacherRating"].describe()

count    60.000000
mean      3.125000
std       0.949797
min       1.050000
25%       2.487500
50%       3.275000
75%       3.827500
max       4.970000
Name: TeacherRating, dtype: float64

In [28]:
teachers_clean[
    (teachers_clean["Age"] < 18) |
    (teachers_clean["YearsOfExperience"] < 0) |
    (teachers_clean["TeacherRating"] < 0) |
    (teachers_clean["TeacherRating"] > 5)
]

Empty DataFrame
Columns: [TeacherID, TeacherName, Age, Gender, Expertise, YearsOfExperience, TeacherRating]
Index: []

## Validate Courses

In [29]:
courses_clean["CoursePrice"].describe()

count     60.000000
mean      92.986333
std      153.601506
min        0.000000
25%        0.000000
50%        0.000000
75%      133.615000
max      490.900000
Name: CoursePrice, dtype: float64

In [30]:
courses_clean["CourseDuration"].describe()

count    60.000000
mean     27.632500
std      16.092578
min       1.200000
25%      14.500000
50%      28.505000
75%      43.012500
max      49.730000
Name: CourseDuration, dtype: float64

In [31]:
courses_clean["CourseRating"].describe()

count    60.000000
mean      3.097833
std       1.171232
min       1.130000
25%       2.107500
50%       3.065000
75%       4.102500
max       4.940000
Name: CourseRating, dtype: float64

## Validate Transactions

In [32]:
transactions_clean["TransactionDate"].describe()

count                         10000
mean     2025-07-01 03:50:32.640000
min             2025-01-01 00:00:00
25%             2025-04-02 00:00:00
50%             2025-06-30 00:00:00
75%             2025-09-28 00:00:00
max             2025-12-30 00:00:00
Name: TransactionDate, dtype: object

In [33]:
transactions_clean["TransactionDate"].isnull().sum()

np.int64(0)

In [34]:
transactions_clean["Amount"].describe()

count    10000.000000
mean        91.132347
std        152.063524
min          0.000000
25%          0.000000
50%          0.000000
75%        119.040000
max        490.900000
Name: Amount, dtype: float64

## Validate PaymentMethod

In [35]:
transactions_clean["PaymentMethod"].value_counts()

PaymentMethod
PayPal           3389
Credit Card      3333
Bank Transfer    3278
Name: count, dtype: int64

In [36]:
transactions_clean["PaymentMethod"].unique()

<ArrowStringArray>
['PayPal', 'Bank Transfer', 'Credit Card']
Length: 3, dtype: str

## Referential integrity

In [37]:
invalid_users = transactions_clean[
    ~transactions_clean["UserID"].isin(users_clean["UserID"])
]

print("Invalid UserIDs:", len(invalid_users))

Invalid UserIDs: 0

In [38]:
invalid_courses = transactions_clean[
    ~transactions_clean["CourseID"].isin(courses_clean["CourseID"])
]

print("Invalid CourseIDs:", len(invalid_courses))

Invalid CourseIDs: 0

In [39]:
invalid_teachers = transactions_clean[
    ~transactions_clean["TeacherID"].isin(teachers_clean["TeacherID"])
]

print("Invalid TeacherIDs:", len(invalid_teachers))

Invalid TeacherIDs: 0

## Recheck Data Types

In [40]:
print(users_clean.dtypes)
print(teachers_clean.dtypes)
print(courses_clean.dtypes)
print(transactions_clean.dtypes)

UserID        str
UserName      str
Age         int64
Gender        str
Email         str
dtype: object
TeacherID                str
TeacherName              str
Age                    int64
Gender                   str
Expertise                str
YearsOfExperience      int64
TeacherRating        float64
dtype: object
CourseID              str
CourseName            str
CourseCategory        str
CourseType            str
CourseLevel           str
CoursePrice       float64
CourseDuration    float64
CourseRating      float64
dtype: object
TransactionID                 str
UserID                        str
CourseID                      str
TransactionDate    datetime64[us]
Amount                    float64
PaymentMethod                 str
TeacherID                     str
dtype: object

## Final Cleaning Validations

In [41]:
print("FINAL DATASET SHAPES")
print("--------------------")

print("Users:", users_clean.shape)
print("Teachers:", teachers_clean.shape)
print("Courses:", courses_clean.shape)
print("Transactions:", transactions_clean.shape)

FINAL DATASET SHAPES
--------------------
Users: (3000, 5)
Teachers: (60, 7)
Courses: (60, 8)
Transactions: (10000, 7)

In [42]:
print("\nFINAL MISSING VALUES")

print("Users:", users_clean.isnull().sum().sum())
print("Teachers:", teachers_clean.isnull().sum().sum())
print("Courses:", courses_clean.isnull().sum().sum())
print("Transactions:", transactions_clean.isnull().sum().sum())

FINAL MISSING VALUES
Users: 0
Teachers: 0
Courses: 0
Transactions: 0

In [43]:
print("\nFINAL DUPLICATE ROWS")

print("Users:", users_clean.duplicated().sum())
print("Teachers:", teachers_clean.duplicated().sum())
print("Courses:", courses_clean.duplicated().sum())
print("Transactions:", transactions_clean.duplicated().sum())

FINAL DUPLICATE ROWS
Users: 0
Teachers: 0
Courses: 0
Transactions: 0

## Saving the cleaned work

In [44]:
from pathlib import Path
import pandas as pd

# Create the cleaned_data folder
cleaned_folder = Path(r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\cleaned_data")
cleaned_folder.mkdir(parents=True, exist_ok=True)

# File to save
cleaned_file_path = cleaned_folder / "EduPro_Cleaned.xlsx"

# Save all cleaned sheets
with pd.ExcelWriter(cleaned_file_path, engine="openpyxl") as writer:
    users_clean.to_excel(writer, sheet_name="Users", index=False)
    teachers_clean.to_excel(writer, sheet_name="Teachers", index=False)
    courses_clean.to_excel(writer, sheet_name="Courses", index=False)
    transactions_clean.to_excel(writer, sheet_name="Transactions", index=False)

print(f"Cleaned workbook saved at:\n{cleaned_file_path}")

Cleaned workbook saved at:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\cleaned_data\EduPro_Cleaned.xlsx

In [45]:
cleaned_excel = pd.ExcelFile(cleaned_file_path)

cleaned_excel.sheet_names

['Users', 'Teachers', 'Courses', 'Transactions']

In [46]:
users_check = pd.read_excel(
    cleaned_file_path,
    sheet_name="Users"
)

teachers_check = pd.read_excel(
    cleaned_file_path,
    sheet_name="Teachers"
)

courses_check = pd.read_excel(
    cleaned_file_path,
    sheet_name="Courses"
)

transactions_check = pd.read_excel(
    cleaned_file_path,
    sheet_name="Transactions"
)

In [47]:
print(users_check.shape)
print(teachers_check.shape)
print(courses_check.shape)
print(transactions_check.shape)

(3000, 5)
(60, 7)
(60, 8)
(10000, 7)