In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
day9_file_path = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx"
)

day10_file_path = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day10_Baseline_Models.xlsx"
)

day11_file_path = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day11_Advanced_Models.xlsx"
)

model_folder = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data"
)

model_folder.mkdir(
    parents=True,
    exist_ok=True
)

day12_file_path = (
    model_folder /
    "EduPro_Day12_Model_Evaluation.xlsx"
)

print("Day 9 input:")
print(day9_file_path)

print("\nDay 10 input:")
print(day10_file_path)

print("\nDay 11 input:")
print(day11_file_path)

print("\nDay 12 output:")
print(day12_file_path)

Day 9 input:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

Day 10 input:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day10_Baseline_Models.xlsx

Day 11 input:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day11_Advanced_Models.xlsx

Day 12 output:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day12_Model_Evaluation.xlsx

## Validating inputs

In [3]:
print("========== INPUT FILE VALIDATION ==========")

print("\nDay 9 exists:")
print(day9_file_path.exists())

print("\nDay 10 exists:")
print(day10_file_path.exists())

print("\nDay 11 exists:")
print(day11_file_path.exists())

========== INPUT FILE VALIDATION ==========

Day 9 exists:
True

Day 10 exists:
True

Day 11 exists:
True

## Load Day 9 datasets

In [4]:
test_data = pd.read_excel(
    day9_file_path,
    sheet_name="Test_Data"
)

y_test = pd.read_excel(
    day9_file_path,
    sheet_name="Y_Test"
)

print("Day 9 test data loaded successfully.")

print("\nTest_Data shape:")
print(test_data.shape)

print("\nY_Test shape:")
print(y_test.shape)

print("\nY_Test columns:")
print(y_test.columns.tolist())

Day 9 test data loaded successfully.

Test_Data shape:
(12, 15)

Y_Test shape:
(12, 2)

Y_Test columns:
['EnrollmentCount', 'CourseRevenue']

## Load Day 10 results

In [5]:
day10_metrics = pd.read_excel(
    day10_file_path,
    sheet_name="Baseline_Metrics"
)

day10_predictions = pd.read_excel(
    day10_file_path,
    sheet_name="Predictions"
)

print("Day 10 results loaded successfully.")

print("\nDay 10 metrics:")
print(day10_metrics)

print("\nDay 10 predictions shape:")
print(day10_predictions.shape)

Day 10 results loaded successfully.

Day 10 metrics:
            Target              Model           MAE          RMSE        R2
0  EnrollmentCount      Mean Baseline     10.444444     11.774502 -0.047209
1    CourseRevenue      Mean Baseline  28413.556771  36217.344701 -0.248807
2  EnrollmentCount  Linear Regression     14.203758     19.812472 -1.965007
3    CourseRevenue  Linear Regression   2725.992334   3542.471175  0.988053

Day 10 predictions shape:
(12, 8)

## Load Day 11 results

In [6]:
day11_metrics = pd.read_excel(
    day11_file_path,
    sheet_name="Advanced_Metrics"
)

day11_all_models = pd.read_excel(
    day11_file_path,
    sheet_name="All_Model_Results"
)

day11_best_models = pd.read_excel(
    day11_file_path,
    sheet_name="Best_Models"
)

day11_predictions = pd.read_excel(
    day11_file_path,
    sheet_name="Predictions"
)

print("Day 11 results loaded successfully.")

print("\nDay 11 advanced metrics:")
print(day11_metrics)

print("\nDay 11 best models:")
print(day11_best_models)

print("\nDay 11 predictions:")
print(day11_predictions.shape)

Day 11 results loaded successfully.

Day 11 advanced metrics:
            Target              Model          MAE         RMSE        R2
0  EnrollmentCount      Random Forest    12.653750    13.539627 -0.384720
1    CourseRevenue      Random Forest  3085.796817  5258.587148  0.973673
2  EnrollmentCount  Gradient Boosting    13.815605    14.701413 -0.632550
3    CourseRevenue  Gradient Boosting  2763.735457  4082.276119  0.984134

Day 11 best models:
            Target         Best_Model          MAE         RMSE        R2
0  EnrollmentCount      Mean Baseline    10.444444    11.774502 -0.047209
1    CourseRevenue  Linear Regression  2725.992334  3542.471175  0.988053

Day 11 predictions:
(12, 8)

## Evaluation 1 — Combine all model metrics

In [7]:
all_model_results = pd.concat(
    [
        day10_metrics,
        day11_metrics
    ],
    ignore_index=True
)

print("========== ALL MODEL METRICS ==========")

all_model_results

========== ALL MODEL METRICS ==========

            Target              Model           MAE          RMSE        R2
0  EnrollmentCount      Mean Baseline     10.444444     11.774502 -0.047209
1    CourseRevenue      Mean Baseline  28413.556771  36217.344701 -0.248807
2  EnrollmentCount  Linear Regression     14.203758     19.812472 -1.965007
3    CourseRevenue  Linear Regression   2725.992334   3542.471175  0.988053
4  EnrollmentCount      Random Forest     12.653750     13.539627 -0.384720
5    CourseRevenue      Random Forest   3085.796817   5258.587148  0.973673
6  EnrollmentCount  Gradient Boosting     13.815605     14.701413 -0.632550
7    CourseRevenue  Gradient Boosting   2763.735457   4082.276119  0.984134

## Evaluation 2 — Rank models

In [10]:
ranked_models = (
    all_model_results
    .sort_values(
        by=["Target", "MAE"]
    )
    .reset_index(drop=True)
)

ranked_models

            Target              Model           MAE          RMSE        R2
0    CourseRevenue  Linear Regression   2725.992334   3542.471175  0.988053
1    CourseRevenue  Gradient Boosting   2763.735457   4082.276119  0.984134
2    CourseRevenue      Random Forest   3085.796817   5258.587148  0.973673
3    CourseRevenue      Mean Baseline  28413.556771  36217.344701 -0.248807
4  EnrollmentCount      Mean Baseline     10.444444     11.774502 -0.047209
5  EnrollmentCount      Random Forest     12.653750     13.539627 -0.384720
6  EnrollmentCount  Gradient Boosting     13.815605     14.701413 -0.632550
7  EnrollmentCount  Linear Regression     14.203758     19.812472 -1.965007

### Add model rankings

In [12]:
ranked_models["MAE_Rank"] = (
    ranked_models
    .groupby("Target")["MAE"]
    .rank(
        method="min",
        ascending=True
    )
)

ranked_models["RMSE_Rank"] = (
    ranked_models
    .groupby("Target")["RMSE"]
    .rank(
        method="min",
        ascending=True
    )
)

ranked_models["R2_Rank"] = (
    ranked_models
    .groupby("Target")["R2"]
    .rank(
        method="min",
        ascending=False
    )
)

ranked_models

,Target,Model,MAE,RMSE,R2,MAE_Rank,RMSE_Rank,R2_Rank
0,CourseRevenue,Linear Regression,2725.992334,3542.471175,0.988053,1.0,1.0,1.0
1,CourseRevenue,Gradient Boosting,2763.735457,4082.276119,0.984134,2.0,2.0,2.0
2,CourseRevenue,Random Forest,3085.796817,5258.587148,0.973673,3.0,3.0,3.0
3,CourseRevenue,Mean Baseline,28413.556771,36217.344701,-0.248807,4.0,4.0,4.0
4,EnrollmentCount,Mean Baseline,10.444444,11.774502,-0.047209,1.0,1.0,1.0
5,EnrollmentCount,Random Forest,12.653750,13.539627,-0.384720,2.0,2.0,2.0
6,EnrollmentCount,Gradient Boosting,13.815605,14.701413,-0.632550,3.0,3.0,3.0
7,EnrollmentCount,Linear Regression,14.203758,19.812472,-1.965007,4.0,4.0,4.0

## Evaluation 3 — Compare against Mean Baseline

In [13]:
baseline_results = (
    all_model_results[
        all_model_results["Model"] == "Mean Baseline"
    ][
        ["Target", "MAE", "RMSE", "R2"]
    ]
    .rename(
        columns={
            "MAE": "Baseline_MAE",
            "RMSE": "Baseline_RMSE",
            "R2": "Baseline_R2"
        }
    )
)

baseline_results

            Target  Baseline_MAE  Baseline_RMSE  Baseline_R2
0  EnrollmentCount     10.444444      11.774502    -0.047209
1    CourseRevenue  28413.556771   36217.344701    -0.248807

### Calculate improvement

In [14]:
evaluation_comparison = all_model_results.merge(
    baseline_results,
    on="Target",
    how="left"
)

evaluation_comparison["MAE_Improvement"] = (
    evaluation_comparison["Baseline_MAE"]
    - evaluation_comparison["MAE"]
)

evaluation_comparison["RMSE_Improvement"] = (
    evaluation_comparison["Baseline_RMSE"]
    - evaluation_comparison["RMSE"]
)

evaluation_comparison["MAE_Improvement_%"] = (
    evaluation_comparison["MAE_Improvement"]
    / evaluation_comparison["Baseline_MAE"]
) * 100

evaluation_comparison["RMSE_Improvement_%"] = (
    evaluation_comparison["RMSE_Improvement"]
    / evaluation_comparison["Baseline_RMSE"]
) * 100

evaluation_comparison.round(3)

,Target,Model,MAE,RMSE,R2,Baseline_MAE,Baseline_RMSE,Baseline_R2,MAE_Improvement,RMSE_Improvement,MAE_Improvement_%,RMSE_Improvement_%
0,EnrollmentCount,Mean Baseline,10.444,11.775,-0.047,10.444,11.775,-0.047,0.000,0.000,0.000,0.000
1,CourseRevenue,Mean Baseline,28413.557,36217.345,-0.249,28413.557,36217.345,-0.249,0.000,0.000,0.000,0.000
2,EnrollmentCount,Linear Regression,14.204,19.812,-1.965,10.444,11.775,-0.047,-3.759,-8.038,-35.993,-68.266
3,CourseRevenue,Linear Regression,2725.992,3542.471,0.988,28413.557,36217.345,-0.249,25687.564,32674.874,90.406,90.219
4,EnrollmentCount,Random Forest,12.654,13.540,-0.385,10.444,11.775,-0.047,-2.209,-1.765,-21.153,-14.991
5,CourseRevenue,Random Forest,3085.797,5258.587,0.974,28413.557,36217.345,-0.249,25327.760,30958.758,89.140,85.480
6,EnrollmentCount,Gradient Boosting,13.816,14.701,-0.633,10.444,11.775,-0.047,-3.371,-2.927,-32.277,-24.858
7,CourseRevenue,Gradient Boosting,2763.735,4082.276,0.984,28413.557,36217.345,-0.249,25649.821,32135.069,90.273,88.728

## Evaluation 4 — Identify models that actually beat baseline

In [15]:
evaluation_comparison["Beats_Baseline"] = (
    evaluation_comparison["MAE_Improvement"] > 0
)

evaluation_comparison[
    [
        "Target",
        "Model",
        "MAE",
        "Baseline_MAE",
        "MAE_Improvement",
        "MAE_Improvement_%",
        "Beats_Baseline"
    ]
].round(3)

,Target,Model,MAE,Baseline_MAE,MAE_Improvement,MAE_Improvement_%,Beats_Baseline
0,EnrollmentCount,Mean Baseline,10.444,10.444,0.000,0.000,False
1,CourseRevenue,Mean Baseline,28413.557,28413.557,0.000,0.000,False
2,EnrollmentCount,Linear Regression,14.204,10.444,-3.759,-35.993,False
3,CourseRevenue,Linear Regression,2725.992,28413.557,25687.564,90.406,True
4,EnrollmentCount,Random Forest,12.654,10.444,-2.209,-21.153,False
5,CourseRevenue,Random Forest,3085.797,28413.557,25327.760,89.140,True
6,EnrollmentCount,Gradient Boosting,13.816,10.444,-3.371,-32.277,False
7,CourseRevenue,Gradient Boosting,2763.735,28413.557,25649.821,90.273,True

## Evaluation 5 — Select best predictive model

In [16]:
best_evaluated_models = []

for target in ["EnrollmentCount", "CourseRevenue"]:

    target_results = evaluation_comparison[
        evaluation_comparison["Target"] == target
    ].copy()

    predictive_models = target_results[
        target_results["Model"] != "Mean Baseline"
    ]

    best_row = predictive_models.loc[
        predictive_models["MAE"].idxmin()
    ]

    best_evaluated_models.append(
        {
            "Target": target,
            "Best_Predictive_Model": best_row["Model"],
            "MAE": best_row["MAE"],
            "RMSE": best_row["RMSE"],
            "R2": best_row["R2"],
            "Beats_Baseline": best_row["Beats_Baseline"],
            "MAE_Improvement_%": best_row["MAE_Improvement_%"]
        }
    )

best_predictive_models_df = pd.DataFrame(
    best_evaluated_models
)

best_predictive_models_df.round(3)

,Target,Best_Predictive_Model,MAE,RMSE,R2,Beats_Baseline,MAE_Improvement_%
0,EnrollmentCount,Random Forest,12.654,13.540,-0.385,False,-21.153
1,CourseRevenue,Linear Regression,2725.992,3542.471,0.988,True,90.406

## Evaluation 6 — Actual vs predicted

In [17]:
prediction_evaluation = day11_predictions.copy()

print("Prediction evaluation dataset:")
print(prediction_evaluation.shape)

prediction_evaluation.head()

Prediction evaluation dataset:
(12, 8)

,CourseID,CourseName,Actual_EnrollmentCount,Random_Forest_EnrollmentCount,Gradient_Boosting_EnrollmentCount,Actual_CourseRevenue,Random_Forest_CourseRevenue,Gradient_Boosting_CourseRevenue
0,CR00050,Computer Vision,174,164.90,161.13,85416.60,73410.27,79770.17
1,CR00036,Agile Project Management,177,160.42,159.81,0.00,0.00,91.23
2,CR00049,Deep Learning,163,161.74,164.99,67728.13,66359.73,73135.92
3,CR00002,Java Programming,149,162.66,164.80,0.00,0.00,91.23
4,CR00055,Full-Stack Web Development,178,161.98,163.63,10202.96,10192.78,8923.86

## Evaluation 7 — Calculate prediction errors

In [18]:
prediction_evaluation["RF_Enrollment_Error"] = (
    prediction_evaluation["Random_Forest_EnrollmentCount"]
    - prediction_evaluation["Actual_EnrollmentCount"]
)

prediction_evaluation["GB_Enrollment_Error"] = (
    prediction_evaluation["Gradient_Boosting_EnrollmentCount"]
    - prediction_evaluation["Actual_EnrollmentCount"]
)

prediction_evaluation["RF_Revenue_Error"] = (
    prediction_evaluation["Random_Forest_CourseRevenue"]
    - prediction_evaluation["Actual_CourseRevenue"]
)

prediction_evaluation["GB_Revenue_Error"] = (
    prediction_evaluation["Gradient_Boosting_CourseRevenue"]
    - prediction_evaluation["Actual_CourseRevenue"]
)

prediction_evaluation.round(2)

,CourseID,CourseName,Actual_EnrollmentCount,Random_Forest_EnrollmentCount,Gradient_Boosting_EnrollmentCount,Actual_CourseRevenue,Random_Forest_CourseRevenue,Gradient_Boosting_CourseRevenue,RF_Enrollment_Error,GB_Enrollment_Error,RF_Revenue_Error,GB_Revenue_Error
0,CR00050,Computer Vision,174,164.90,161.13,85416.60,73410.27,79770.17,-9.10,-12.87,-12006.33,-5646.43
1,CR00036,Agile Project Management,177,160.42,159.81,0.00,0.00,91.23,-16.58,-17.19,0.00,91.23
2,CR00049,Deep Learning,163,161.74,164.99,67728.13,66359.73,73135.92,-1.26,1.99,-1368.40,5407.79
3,CR00002,Java Programming,149,162.66,164.80,0.00,0.00,91.23,13.66,15.80,0.00,91.23
4,CR00055,Full-Stack Web Development,178,161.98,163.63,10202.96,10192.78,8923.86,-16.02,-14.37,-10.18,-1279.10
5,CR00034,Data Encryption,150,160.86,158.69,59139.00,52664.50,52489.73,10.86,8.69,-6474.50,-6649.27
6,CR00035,Cyber Threat Intelligence,179,162.16,163.74,0.00,0.00,91.23,-16.84,-15.26,0.00,91.23
7,CR00045,Financial Modeling,172,164.77,164.30,0.00,0.00,91.23,-7.23,-7.70,0.00,91.23
8,CR00020,Email Marketing,155,169.80,172.81,0.00,0.00,91.23,14.80,17.81,0.00,91.23
9,CR00048,AI Ethics,186,166.64,168.24,0.00,223.08,91.23,-19.36,-17.76,223.08,91.23
10,CR00040,Leadership in Projects,174,158.90,158.23,57070.26,48251.98,50261.00,-15.10,-15.77,-8818.28,-6809.26
11,CR00039,Project Planning,167,155.97,146.42,57900.57,49771.78,51074.99,-11.03,-20.58,-8128.79,-6825.58

## Evaluation 8 — Absolute errors

In [19]:
prediction_evaluation["RF_Enrollment_Absolute_Error"] = (
    prediction_evaluation["RF_Enrollment_Error"].abs()
)

prediction_evaluation["GB_Enrollment_Absolute_Error"] = (
    prediction_evaluation["GB_Enrollment_Error"].abs()
)

prediction_evaluation["RF_Revenue_Absolute_Error"] = (
    prediction_evaluation["RF_Revenue_Error"].abs()
)

prediction_evaluation["GB_Revenue_Absolute_Error"] = (
    prediction_evaluation["GB_Revenue_Error"].abs()
)

prediction_evaluation.round(2)

,CourseID,CourseName,Actual_EnrollmentCount,Random_Forest_EnrollmentCount,Gradient_Boosting_EnrollmentCount,Actual_CourseRevenue,Random_Forest_CourseRevenue,Gradient_Boosting_CourseRevenue,RF_Enrollment_Error,GB_Enrollment_Error,RF_Revenue_Error,GB_Revenue_Error,RF_Enrollment_Absolute_Error,GB_Enrollment_Absolute_Error,RF_Revenue_Absolute_Error,GB_Revenue_Absolute_Error
0,CR00050,Computer Vision,174,164.90,161.13,85416.60,73410.27,79770.17,-9.10,-12.87,-12006.33,-5646.43,9.10,12.87,12006.33,5646.43
1,CR00036,Agile Project Management,177,160.42,159.81,0.00,0.00,91.23,-16.58,-17.19,0.00,91.23,16.58,17.19,0.00,91.23
2,CR00049,Deep Learning,163,161.74,164.99,67728.13,66359.73,73135.92,-1.26,1.99,-1368.40,5407.79,1.26,1.99,1368.40,5407.79
3,CR00002,Java Programming,149,162.66,164.80,0.00,0.00,91.23,13.66,15.80,0.00,91.23,13.66,15.80,0.00,91.23
4,CR00055,Full-Stack Web Development,178,161.98,163.63,10202.96,10192.78,8923.86,-16.02,-14.37,-10.18,-1279.10,16.02,14.37,10.18,1279.10
5,CR00034,Data Encryption,150,160.86,158.69,59139.00,52664.50,52489.73,10.86,8.69,-6474.50,-6649.27,10.86,8.69,6474.50,6649.27
6,CR00035,Cyber Threat Intelligence,179,162.16,163.74,0.00,0.00,91.23,-16.84,-15.26,0.00,91.23,16.84,15.26,0.00,91.23
7,CR00045,Financial Modeling,172,164.77,164.30,0.00,0.00,91.23,-7.23,-7.70,0.00,91.23,7.23,7.70,0.00,91.23
8,CR00020,Email Marketing,155,169.80,172.81,0.00,0.00,91.23,14.80,17.81,0.00,91.23,14.80,17.81,0.00,91.23
9,CR00048,AI Ethics,186,166.64,168.24,0.00,223.08,91.23,-19.36,-17.76,223.08,91.23,19.36,17.76,223.08,91.23
10,CR00040,Leadership in Projects,174,158.90,158.23,57070.26,48251.98,50261.00,-15.10,-15.77,-8818.28,-6809.26,15.10,15.77,8818.28,6809.26
11,CR00039,Project Planning,167,155.97,146.42,57900.57,49771.78,51074.99,-11.03,-20.58,-8128.79,-6825.58,11.03,20.58,8128.79,6825.58

## Evaluation 9 — Revenue zero-value evaluation

In [20]:
revenue_zero_evaluation = prediction_evaluation[
    prediction_evaluation["Actual_CourseRevenue"] == 0
].copy()

revenue_nonzero_evaluation = prediction_evaluation[
    prediction_evaluation["Actual_CourseRevenue"] > 0
].copy()

print("Zero-revenue test observations:")
print(len(revenue_zero_evaluation))

print("\nNon-zero-revenue test observations:")
print(len(revenue_nonzero_evaluation))

Zero-revenue test observations:
6

Non-zero-revenue test observations:
6

In [21]:
print("========== ZERO REVENUE PREDICTIONS ==========")

revenue_zero_evaluation[
    [
        "CourseID",
        "CourseName",
        "Actual_CourseRevenue",
        "Random_Forest_CourseRevenue",
        "Gradient_Boosting_CourseRevenue"
    ]
].round(2)

========== ZERO REVENUE PREDICTIONS ==========

,CourseID,CourseName,Actual_CourseRevenue,Random_Forest_CourseRevenue,Gradient_Boosting_CourseRevenue
1,CR00036,Agile Project Management,0.0,0.00,91.23
3,CR00002,Java Programming,0.0,0.00,91.23
6,CR00035,Cyber Threat Intelligence,0.0,0.00,91.23
7,CR00045,Financial Modeling,0.0,0.00,91.23
8,CR00020,Email Marketing,0.0,0.00,91.23
9,CR00048,AI Ethics,0.0,223.08,91.23

## Evaluation 10 — Non-zero revenue performance

In [22]:
nonzero_revenue_metrics = []

for model_name, prediction_column in [
    (
        "Random Forest",
        "Random_Forest_CourseRevenue"
    ),
    (
        "Gradient Boosting",
        "Gradient_Boosting_CourseRevenue"
    )
]:

    actual = revenue_nonzero_evaluation[
        "Actual_CourseRevenue"
    ]

    predictions = revenue_nonzero_evaluation[
        prediction_column
    ]

    nonzero_revenue_metrics.append(
        {
            "Model": model_name,
            "MAE": mean_absolute_error(
                actual,
                predictions
            ),
            "RMSE": np.sqrt(
                mean_squared_error(
                    actual,
                    predictions
                )
            ),
            "R2": r2_score(
                actual,
                predictions
            )
        }
    )

nonzero_revenue_metrics_df = pd.DataFrame(
    nonzero_revenue_metrics
)

nonzero_revenue_metrics_df.round(3)

               Model       MAE      RMSE     R2
0      Random Forest  6134.413  7436.207  0.893
1  Gradient Boosting  5436.238  5772.490  0.936

## Evaluation 11 — Residual summary

In [23]:
residual_summary = pd.DataFrame(
    {
        "Metric": [
            "RF Enrollment Mean Error",
            "RF Enrollment Mean Absolute Error",
            "GB Enrollment Mean Error",
            "GB Enrollment Mean Absolute Error",
            "RF Revenue Mean Error",
            "RF Revenue Mean Absolute Error",
            "GB Revenue Mean Error",
            "GB Revenue Mean Absolute Error"
        ],
        "Value": [
            prediction_evaluation["RF_Enrollment_Error"].mean(),
            prediction_evaluation["RF_Enrollment_Absolute_Error"].mean(),
            prediction_evaluation["GB_Enrollment_Error"].mean(),
            prediction_evaluation["GB_Enrollment_Absolute_Error"].mean(),
            prediction_evaluation["RF_Revenue_Error"].mean(),
            prediction_evaluation["RF_Revenue_Absolute_Error"].mean(),
            prediction_evaluation["GB_Revenue_Error"].mean(),
            prediction_evaluation["GB_Revenue_Absolute_Error"].mean()
        ]
    }
)

residual_summary.round(3)

                              Metric     Value
0           RF Enrollment Mean Error    -6.100
1  RF Enrollment Mean Absolute Error    12.653
2           GB Enrollment Mean Error    -6.434
3  GB Enrollment Mean Absolute Error    13.816
4              RF Revenue Mean Error -3048.617
5     RF Revenue Mean Absolute Error  3085.797
6              GB Revenue Mean Error -1771.206
7     GB Revenue Mean Absolute Error  2763.734

## Evaluation 12 — Final model decision

In [24]:
final_model_decision = pd.DataFrame(
    [
        {
            "Target": "EnrollmentCount",
            "Selected_Model": "Mean Baseline",
            "Reason": (
                "Advanced predictive models did not outperform "
                "the mean baseline on MAE."
            )
        },
        {
            "Target": "CourseRevenue",
            "Selected_Model": "Linear Regression",
            "Reason": (
                "Lowest MAE and RMSE among evaluated models "
                "and highest R2."
            )
        }
    ]
)

final_model_decision

,Target,Selected_Model,Reason
0,EnrollmentCount,Mean Baseline,Advanced predictive models did not outperform ...
1,CourseRevenue,Linear Regression,Lowest MAE and RMSE among evaluated models and...

## Evaluation 13 — Overall project evaluation

In [25]:
overall_evaluation = pd.DataFrame(
    [
        {
            "Target": "EnrollmentCount",
            "Best_Model": "Mean Baseline",
            "MAE": 10.444444,
            "RMSE": 11.774502,
            "R2": -0.047209,
            "Model_Status": "Needs improvement"
        },
        {
            "Target": "CourseRevenue",
            "Best_Model": "Linear Regression",
            "MAE": 2725.992334,
            "RMSE": 3542.471175,
            "R2": 0.988053,
            "Model_Status": "Strong predictive performance"
        }
    ]
)

overall_evaluation.round(
    {
        "MAE": 3,
        "RMSE": 3,
        "R2": 4
    }
)

,Target,Best_Model,MAE,RMSE,R2,Model_Status
0,EnrollmentCount,Mean Baseline,10.444,11.775,-0.0472,Needs improvement
1,CourseRevenue,Linear Regression,2725.992,3542.471,0.9881,Strong predictive performance

## Saving Day 12

In [26]:
with pd.ExcelWriter(
    day12_file_path,
    engine="openpyxl"
) as writer:

    all_model_results.to_excel(
        writer,
        sheet_name="All_Model_Metrics",
        index=False
    )

    ranked_models.to_excel(
        writer,
        sheet_name="Model_Rankings",
        index=False
    )

    evaluation_comparison.to_excel(
        writer,
        sheet_name="Baseline_Comparison",
        index=False
    )

    best_predictive_models_df.to_excel(
        writer,
        sheet_name="Best_Predictive_Models",
        index=False
    )

    prediction_evaluation.to_excel(
        writer,
        sheet_name="Prediction_Evaluation",
        index=False
    )

    nonzero_revenue_metrics_df.to_excel(
        writer,
        sheet_name="NonZero_Revenue_Evaluation",
        index=False
    )

    residual_summary.to_excel(
        writer,
        sheet_name="Residual_Summary",
        index=False
    )

    final_model_decision.to_excel(
        writer,
        sheet_name="Final_Model_Decision",
        index=False
    )

    overall_evaluation.to_excel(
        writer,
        sheet_name="Overall_Evaluation",
        index=False
    )

print("✅ Day 12 evaluation results saved successfully:")
print(day12_file_path)

✅ Day 12 evaluation results saved successfully:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day12_Model_Evaluation.xlsx

## Reload and Validate

In [27]:
check_all_metrics = pd.read_excel(
    day12_file_path,
    sheet_name="All_Model_Metrics"
)

check_rankings = pd.read_excel(
    day12_file_path,
    sheet_name="Model_Rankings"
)

check_baseline = pd.read_excel(
    day12_file_path,
    sheet_name="Baseline_Comparison"
)

check_best_models = pd.read_excel(
    day12_file_path,
    sheet_name="Best_Predictive_Models"
)

check_predictions = pd.read_excel(
    day12_file_path,
    sheet_name="Prediction_Evaluation"
)

check_decision = pd.read_excel(
    day12_file_path,
    sheet_name="Final_Model_Decision"
)

print("========== DAY 12 OUTPUT VALIDATION ==========")

print("\nAll model metrics:")
print(check_all_metrics.shape)

print("\nModel rankings:")
print(check_rankings.shape)

print("\nBaseline comparison:")
print(check_baseline.shape)

print("\nBest predictive models:")
print(check_best_models.shape)

print("\nPrediction evaluation:")
print(check_predictions.shape)

print("\nFinal model decision:")
print(check_decision.shape)

print("\nOutput file exists:")
print(day12_file_path.exists())

========== DAY 12 OUTPUT VALIDATION ==========

All model metrics:
(8, 5)

Model rankings:
(8, 8)

Baseline comparison:
(8, 13)

Best predictive models:
(2, 7)

Prediction evaluation:
(12, 16)

Final model decision:
(2, 3)

Output file exists:
True

## Final validation

In [28]:
print("==============================================")
print("DAY 12 MODEL EVALUATION VALIDATION")
print("==============================================")

print("\nInput — Day 9:")
print(day9_file_path)

print("\nInput — Day 10:")
print(day10_file_path)

print("\nInput — Day 11:")
print(day11_file_path)

print("\nOutput — Day 12:")
print(day12_file_path)

print("\nModels evaluated:")
print(
    all_model_results["Model"]
    .unique()
    .tolist()
)

print("\nTargets evaluated:")
print(
    all_model_results["Target"]
    .unique()
    .tolist()
)

print("\nBest predictive models:")
print(best_predictive_models_df)

print("\nFinal model decision:")
print(final_model_decision)

print("\nOutput file exists:")
print(day12_file_path.exists())

print("\n==============================================")
print("DAY 12 COMPLETED")
print("==============================================")

==============================================
DAY 12 MODEL EVALUATION VALIDATION
==============================================

Input — Day 9:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

Input — Day 10:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day10_Baseline_Models.xlsx

Input — Day 11:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day11_Advanced_Models.xlsx

Output — Day 12:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day12_Model_Evaluation.xlsx

Models evaluated:
['Mean Baseline', 'Linear Regression', 'Random Forest', 'Gradient Boosting']

Targets evaluated:
['EnrollmentCount', 'CourseRevenue']

Best predictive models:
            Target Best_Predictive_Model          MAE         RMSE        R2  \
0  EnrollmentCount         Random Forest    12.653750    13.539627 -0.384720
1    CourseRevenue     Linear Regression  2725.992334  3542.471175  0.988053

   Beats_Baseline  MAE_Improvement_%
0           False         -21.152926
1            True          90.406015

Final model decision:
            Target     Selected_Model  \
0  EnrollmentCount      Mean Baseline
1    CourseRevenue  Linear Regression

                                              Reason
0  Advanced predictive models did not outperform ...
1  Lowest MAE and RMSE among evaluated models and...

Output file exists:
True

==============================================
DAY 12 COMPLETED
==============================================