In [1]:
import pandas as pd
import numpy as np

from pathlib import Path
from sklearn.model_selection import train_test_split

In [2]:
day8_file_path = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\feature_data\EduPro_Day8_Prediction_Targets.xlsx"
)

print("Day 8 input file:")
print(day8_file_path)

print("File exists:", day8_file_path.exists())

Day 8 input file:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\feature_data\EduPro_Day8_Prediction_Targets.xlsx
File exists: True

In [3]:
prediction_targets = pd.read_excel(
    day8_file_path,
    sheet_name="Prediction_Targets"
)

print("Day 8 dataset loaded successfully.")
print("Shape:", prediction_targets.shape)

Day 8 dataset loaded successfully.
Shape: (60, 15)

## Inspect columns

In [4]:
print("Available columns:")

for i, col in enumerate(prediction_targets.columns, start=1):
    print(f"{i}. {col}")

Available columns:
1. CourseID
2. CourseName
3. CourseCategory
4. CourseType
5. CourseLevel
6. CoursePrice
7. CourseDuration
8. CourseRating
9. TeacherID
10. TeacherName
11. TeacherRating
12. YearsOfExperience
13. Expertise
14. EnrollmentCount
15. CourseRevenue

## Validating Day 8 input

In [5]:
print("========== DAY 8 INPUT VALIDATION ==========")

print("\nDataset shape:")
print(prediction_targets.shape)

print("\nMissing values:")
print(prediction_targets.isnull().sum().sum())

print("\nDuplicate CourseIDs:")
print(prediction_targets["CourseID"].duplicated().sum())

print("\nUnique courses:")
print(prediction_targets["CourseID"].nunique())

========== DAY 8 INPUT VALIDATION ==========

Dataset shape:
(60, 15)

Missing values:
0

Duplicate CourseIDs:
0

Unique courses:
60

## Define Prediction Targets

In [6]:
target_columns = [
    "EnrollmentCount",
    "CourseRevenue"
]

print("Prediction targets:")
print(target_columns)

Prediction targets:
['EnrollmentCount', 'CourseRevenue']

## Define columns to exclude from modeling

In [7]:
identifier_columns = [
    "CourseID",
    "CourseName",
    "TeacherID",
    "TeacherName"
]

print("Identifier columns excluded from modeling:")
print(identifier_columns)

Identifier columns excluded from modeling:
['CourseID', 'CourseName', 'TeacherID', 'TeacherName']

## Create the modeling features list

In [8]:
feature_columns = [
    col
    for col in prediction_targets.columns
    if col not in identifier_columns + target_columns
]

print("Modeling features:")
print(feature_columns)

print("\nNumber of modeling features:")
print(len(feature_columns))

Modeling features:
['CourseCategory', 'CourseType', 'CourseLevel', 'CoursePrice', 'CourseDuration', 'CourseRating', 'TeacherRating', 'YearsOfExperience', 'Expertise']

Number of modeling features:
9

## Create X and y

In [9]:
X = prediction_targets[feature_columns].copy()

y = prediction_targets[target_columns].copy()

print("X shape:")
print(X.shape)

print("\ny shape:")
print(y.shape)

X shape:
(60, 9)

y shape:
(60, 2)

In [10]:
X.head()

,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,TeacherRating,YearsOfExperience,Expertise
0,Artificial Intelligence,Paid,Beginner,490.9,7.55,4.55,4.58,24,Cybersecurity
1,Data Science,Free,Intermediate,0.0,1.20,3.60,2.92,1,Data Science
2,Design,Free,Beginner,0.0,48.19,4.51,1.77,2,Design
3,Data Science,Free,Beginner,0.0,32.64,3.65,2.18,1,Data Science
4,Machine Learning,Free,Advanced,0.0,9.30,1.81,1.39,4,Digital Marketing

In [11]:
y.head()

   EnrollmentCount  CourseRevenue
0              174        85416.6
1              196            0.0
2              155            0.0
3              177            0.0
4              152            0.0

## Check target distribution before splitting

In [12]:
print("========== TARGET DISTRIBUTION ==========")

print("\nEnrollmentCount:")
print(y["EnrollmentCount"].describe())

print("\nCourseRevenue:")
print(y["CourseRevenue"].describe())

========== TARGET DISTRIBUTION ==========

EnrollmentCount:
count     60.000000
mean     166.666667
std       12.523424
min      140.000000
25%      157.500000
50%      166.000000
75%      174.750000
max      196.000000
Name: EnrollmentCount, dtype: float64

CourseRevenue:
count       60.000000
mean     15188.724500
std      25409.721911
min          0.000000
25%          0.000000
50%          0.000000
75%      20858.060000
max      85416.600000
Name: CourseRevenue, dtype: float64

## Important revenue check

In [13]:
print("Zero EnrollmentCount:")
print((y["EnrollmentCount"] == 0).sum())

print("\nZero CourseRevenue:")
print((y["CourseRevenue"] == 0).sum())

Zero EnrollmentCount:
0

Zero CourseRevenue:
38

## Create train/test split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Train/Test split completed.")

Train/Test split completed.

## Check Split sizes

In [15]:
print("========== TRAIN / TEST SHAPES ==========")

print("\nX_train:")
print(X_train.shape)

print("\nX_test:")
print(X_test.shape)

print("\ny_train:")
print(y_train.shape)

print("\ny_test:")
print(y_test.shape)

========== TRAIN / TEST SHAPES ==========

X_train:
(48, 9)

X_test:
(12, 9)

y_train:
(48, 2)

y_test:
(12, 2)

## Verify target distribution in train/test

In [16]:
print("========== TRAIN TARGET DISTRIBUTION ==========")

print("\nEnrollmentCount:")
print(y_train["EnrollmentCount"].describe())

print("\nCourseRevenue:")
print(y_train["CourseRevenue"].describe())


print("\n========== TEST TARGET DISTRIBUTION ==========")

print("\nEnrollmentCount:")
print(y_test["EnrollmentCount"].describe())

print("\nCourseRevenue:")
print(y_test["CourseRevenue"].describe())

========== TRAIN TARGET DISTRIBUTION ==========

EnrollmentCount:
count     48.000000
mean     166.166667
std       12.720119
min      140.000000
25%      157.500000
50%      166.000000
75%      173.000000
max      196.000000
Name: EnrollmentCount, dtype: float64

CourseRevenue:
count       48.000000
mean     11955.540625
std      22112.112826
min          0.000000
25%          0.000000
50%          0.000000
75%      15945.315000
max      84410.160000
Name: CourseRevenue, dtype: float64

========== TEST TARGET DISTRIBUTION ==========

EnrollmentCount:
count     12.000000
mean     168.666667
std       12.017664
min      149.000000
25%      161.000000
50%      173.000000
75%      177.250000
max      186.000000
Name: EnrollmentCount, dtype: float64

CourseRevenue:
count       12.000000
mean     28121.460000
std      33850.351542
min          0.000000
25%          0.000000
50%       5101.480000
75%      58210.177500
max      85416.600000
Name: CourseRevenue, dtype: float64

## Check zero-revenue representation

In [17]:
print("Zero CourseRevenue in training set:")
print((y_train["CourseRevenue"] == 0).sum())

print("\nZero CourseRevenue in test set:")
print((y_test["CourseRevenue"] == 0).sum())

Zero CourseRevenue in training set:
32

Zero CourseRevenue in test set:
6

## Check for train/test overlap

In [18]:
train_indices = X_train.index
test_indices = X_test.index

overlap = set(train_indices).intersection(set(test_indices))

print("Train/Test index overlap:")
print(len(overlap))

Train/Test index overlap:
0

## Verify that all 60 observation are accounted for

In [19]:
total_rows = len(X_train) + len(X_test)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Total rows:", total_rows)
print("Original rows:", len(X))

Training rows: 48
Testing rows: 12
Total rows: 60
Original rows: 60

## Preserve CourseIDs for validation

In [20]:
course_ids = prediction_targets["CourseID"].copy()

course_id_train = course_ids.loc[X_train.index].copy()
course_id_test = course_ids.loc[X_test.index].copy()

print("Training CourseIDs:", len(course_id_train))
print("Testing CourseIDs:", len(course_id_test))

Training CourseIDs: 48
Testing CourseIDs: 12

## Create complete train/test datasets

In [21]:
train_data = prediction_targets.loc[X_train.index].copy()
test_data = prediction_targets.loc[X_test.index].copy()

print("Training dataset:")
print(train_data.shape)

print("\nTesting dataset:")
print(test_data.shape)

Training dataset:
(48, 15)

Testing dataset:
(12, 15)

## Output folder (Day 9)

In [22]:
split_folder = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data"
)

split_folder.mkdir(
    parents=True,
    exist_ok=True
)

print("Output folder:")
print(split_folder)

print("Folder exists:", split_folder.exists())

Output folder:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data
Folder exists: True

In [23]:
day9_file_path = (
    split_folder
    / "EduPro_Day9_Train_Test_Splits.xlsx"
)

print("Day 9 output file:")
print(day9_file_path)

Day 9 output file:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

In [24]:
with pd.ExcelWriter(
    day9_file_path,
    engine="openpyxl"
) as writer:

    train_data.to_excel(
        writer,
        sheet_name="Train_Data",
        index=False
    )

    test_data.to_excel(
        writer,
        sheet_name="Test_Data",
        index=False
    )

    X_train.to_excel(
        writer,
        sheet_name="X_Train",
        index=False
    )

    X_test.to_excel(
        writer,
        sheet_name="X_Test",
        index=False
    )

    y_train.to_excel(
        writer,
        sheet_name="Y_Train",
        index=False
    )

    y_test.to_excel(
        writer,
        sheet_name="Y_Test",
        index=False
    )

print("✅ Day 9 Train/Test datasets saved successfully:")
print(day9_file_path)

✅ Day 9 Train/Test datasets saved successfully:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

In [25]:
check_train = pd.read_excel(
    day9_file_path,
    sheet_name="Train_Data"
)

check_test = pd.read_excel(
    day9_file_path,
    sheet_name="Test_Data"
)

print("Reloaded training dataset:")
print(check_train.shape)

print("\nReloaded testing dataset:")
print(check_test.shape)

Reloaded training dataset:
(48, 15)

Reloaded testing dataset:
(12, 15)

## Day 9 validation

In [26]:
print("========== DAY 9 TRAIN/TEST VALIDATION ==========")

print("\nOriginal dataset rows:")
print(len(prediction_targets))

print("\nTraining rows:")
print(len(train_data))

print("\nTesting rows:")
print(len(test_data))

print("\nTotal split rows:")
print(len(train_data) + len(test_data))

print("\nTraining shape:")
print(X_train.shape)

print("\nTesting shape:")
print(X_test.shape)

print("\nTraining target shape:")
print(y_train.shape)

print("\nTesting target shape:")
print(y_test.shape)

print("\nTrain/Test index overlap:")
print(len(overlap))

print("\nTraining missing values:")
print(X_train.isnull().sum().sum() + y_train.isnull().sum().sum())

print("\nTesting missing values:")
print(X_test.isnull().sum().sum() + y_test.isnull().sum().sum())

print("\nOutput file:")
print(day9_file_path)

print("\n==============================================")
print("DAY 9 COMPLETED")
print("==============================================")

========== DAY 9 TRAIN/TEST VALIDATION ==========

Original dataset rows:
60

Training rows:
48

Testing rows:
12

Total split rows:
60

Training shape:
(48, 9)

Testing shape:
(12, 9)

Training target shape:
(48, 2)

Testing target shape:
(12, 2)

Train/Test index overlap:
0

Training missing values:
0

Testing missing values:
0

Output file:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

==============================================
DAY 9 COMPLETED
==============================================