In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
day9_file_path = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx"
)

day10_file_path = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day10_Baseline_Models.xlsx"
)

print("Day 9 input file:")
print(day9_file_path)

print("\nDay 9 file exists:")
print(day9_file_path.exists())

print("\nDay 10 input file:")
print(day10_file_path)

print("\nDay 10 file exists:")
print(day10_file_path.exists())

Day 9 input file:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

Day 9 file exists:
True

Day 10 input file:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day10_Baseline_Models.xlsx

Day 10 file exists:
True

## Load Day 9 datasets

In [9]:
train_data = pd.read_excel(
    day9_file_path,
    sheet_name="Train_Data"
)

test_data = pd.read_excel(
    day9_file_path,
    sheet_name="Test_Data"
)

X_train = pd.read_excel(
    day9_file_path,
    sheet_name="X_Train"
)

X_test = pd.read_excel(
    day9_file_path,
    sheet_name="X_Test"
)

y_train = pd.read_excel(
    day9_file_path,
    sheet_name="Y_Train"
)

y_test = pd.read_excel(
    day9_file_path,
    sheet_name="Y_Test"
)

print("Day 9 datasets loaded successfully.")

print("\nTrain_Data:", train_data.shape)
print("Test_Data:", test_data.shape)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

Day 9 datasets loaded successfully.

Train_Data: (48, 15)
Test_Data: (12, 15)
X_train: (48, 9)
X_test: (12, 9)
y_train: (48, 2)
y_test: (12, 2)

## Load Day 10 baseline results

In [10]:
day10_metrics = pd.read_excel(
    day10_file_path,
    sheet_name="Baseline_Metrics"
)

day10_comparison = pd.read_excel(
    day10_file_path,
    sheet_name="Model_Comparison"
)

day10_predictions = pd.read_excel(
    day10_file_path,
    sheet_name="Predictions"
)

print("Day 10 results loaded successfully.")

print("\nDay 10 metrics:")
print(day10_metrics)

print("\nDay 10 model comparison:")
print(day10_comparison)

Day 10 results loaded successfully.

Day 10 metrics:
            Target              Model           MAE          RMSE        R2
0  EnrollmentCount      Mean Baseline     10.444444     11.774502 -0.047209
1    CourseRevenue      Mean Baseline  28413.556771  36217.344701 -0.248807
2  EnrollmentCount  Linear Regression     14.203758     19.812472 -1.965007
3    CourseRevenue  Linear Regression   2725.992334   3542.471175  0.988053

Day 10 model comparison:
            Target  Mean_Baseline_MAE  Linear_Regression_MAE  MAE_Improvement  \
0  EnrollmentCount          10.444444              14.203758        -3.759314
1    CourseRevenue       28413.556771            2725.992334     25687.564437

   Mean_Baseline_RMSE  Linear_Regression_RMSE  RMSE_Improvement  \
0           11.774502               19.812472         -8.037970
1        36217.344701             3542.471175      32674.873526

   Mean_Baseline_R2  Linear_Regression_R2
0         -0.047209             -1.965007
1         -0.248807              0.988053

## Validate Day 11 inputs

In [11]:
print("========== DAY 11 INPUT VALIDATION ==========")

print("\nTraining rows:")
print(len(X_train))

print("\nTesting rows:")
print(len(X_test))

print("\nTraining features:")
print(X_train.shape)

print("\nTesting features:")
print(X_test.shape)

print("\nTraining targets:")
print(y_train.shape)

print("\nTesting targets:")
print(y_test.shape)

print("\nTraining missing values:")
print(
    X_train.isnull().sum().sum()
    +
    y_train.isnull().sum().sum()
)

print("\nTesting missing values:")
print(
    X_test.isnull().sum().sum()
    +
    y_test.isnull().sum().sum()
)

========== DAY 11 INPUT VALIDATION ==========

Training rows:
48

Testing rows:
12

Training features:
(48, 9)

Testing features:
(12, 9)

Training targets:
(48, 2)

Testing targets:
(12, 2)

Training missing values:
0

Testing missing values:
0

## Define targets and features

In [12]:
target_columns = [
    "EnrollmentCount",
    "CourseRevenue"
]

feature_columns = [
    "CourseCategory",
    "CourseType",
    "CourseLevel",
    "CoursePrice",
    "CourseDuration",
    "CourseRating",
    "TeacherRating",
    "YearsOfExperience",
    "Expertise"
]

print("Targets:")
print(target_columns)

print("\nFeatures:")
print(feature_columns)

print("\nNumber of features:")
print(len(feature_columns))

Targets:
['EnrollmentCount', 'CourseRevenue']

Features:
['CourseCategory', 'CourseType', 'CourseLevel', 'CoursePrice', 'CourseDuration', 'CourseRating', 'TeacherRating', 'YearsOfExperience', 'Expertise']

Number of features:
9

## Identify feature types

In [13]:
categorical_features = [
    "CourseCategory",
    "CourseType",
    "CourseLevel",
    "Expertise"
]

numerical_features = [
    "CoursePrice",
    "CourseDuration",
    "CourseRating",
    "TeacherRating",
    "YearsOfExperience"
]

print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
['CourseCategory', 'CourseType', 'CourseLevel', 'Expertise']

Numerical features:
['CoursePrice', 'CourseDuration', 'CourseRating', 'TeacherRating', 'YearsOfExperience']

## Create preprocessing pipeline

In [14]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numerical_features
        )
    ]
)

print("Advanced-model preprocessing pipeline created successfully.")

Advanced-model preprocessing pipeline created successfully.

## Create Random Forest models

In [15]:
random_forest_enrollment = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestRegressor(
                n_estimators=200,
                random_state=42,
                max_depth=None,
                min_samples_split=2,
                min_samples_leaf=1
            )
        )
    ]
)

random_forest_revenue = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestRegressor(
                n_estimators=200,
                random_state=42,
                max_depth=None,
                min_samples_split=2,
                min_samples_leaf=1
            )
        )
    ]
)

print("Random Forest models created successfully.")

Random Forest models created successfully.

## Train Random Forest for EnrollmentCount

In [16]:
random_forest_enrollment.fit(
    X_train,
    y_train["EnrollmentCount"]
)

rf_enrollment_predictions = (
    random_forest_enrollment.predict(X_test)
)

print("Random Forest trained for EnrollmentCount.")

print("\nFirst 5 predictions:")
print(rf_enrollment_predictions[:5])

Random Forest trained for EnrollmentCount.

First 5 predictions:
[164.895 160.42  161.74  162.655 161.975]

## Train Random Forest for CourseRevenue

In [17]:
random_forest_revenue.fit(
    X_train,
    y_train["CourseRevenue"]
)

rf_revenue_predictions = (
    random_forest_revenue.predict(X_test)
)

print("Random Forest trained for CourseRevenue.")

print("\nFirst 5 predictions:")
print(rf_revenue_predictions[:5])

Random Forest trained for CourseRevenue.

First 5 predictions:
[73410.2712     0.     66359.7337     0.     10192.7794]

## Create Gradient Boosting models

In [18]:
gradient_boosting_enrollment = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            GradientBoostingRegressor(
                n_estimators=100,
                learning_rate=0.05,
                max_depth=2,
                random_state=42
            )
        )
    ]
)

gradient_boosting_revenue = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            GradientBoostingRegressor(
                n_estimators=100,
                learning_rate=0.05,
                max_depth=2,
                random_state=42
            )
        )
    ]
)

print("Gradient Boosting models created successfully.")

Gradient Boosting models created successfully.

## Train Gradient Boosting for EnrollmentCount

In [19]:
gradient_boosting_enrollment.fit(
    X_train,
    y_train["EnrollmentCount"]
)

gb_enrollment_predictions = (
    gradient_boosting_enrollment.predict(X_test)
)

print("Gradient Boosting trained for EnrollmentCount.")

print("\nFirst 5 predictions:")
print(gb_enrollment_predictions[:5])

Gradient Boosting trained for EnrollmentCount.

First 5 predictions:
[161.12648011 159.81416644 164.9945173  164.79504408 163.63499748]

## Train Gradient Boosting for CourseRevenue

In [20]:
gradient_boosting_revenue.fit(
    X_train,
    y_train["CourseRevenue"]
)

gb_revenue_predictions = (
    gradient_boosting_revenue.predict(X_test)
)

print("Gradient Boosting trained for CourseRevenue.")

print("\nFirst 5 predictions:")
print(gb_revenue_predictions[:5])

Gradient Boosting trained for CourseRevenue.

First 5 predictions:
[79770.16528878    91.23227451 73135.92128753    91.23227451
  8923.85738993]

## Calculate advanced model metrics

In [21]:
advanced_results = []

models_and_predictions = {
    "Random Forest": {
        "EnrollmentCount": rf_enrollment_predictions,
        "CourseRevenue": rf_revenue_predictions
    },
    "Gradient Boosting": {
        "EnrollmentCount": gb_enrollment_predictions,
        "CourseRevenue": gb_revenue_predictions
    }
}

for model_name, target_predictions in models_and_predictions.items():

    for target in target_columns:

        actual = y_test[target]

        predictions = target_predictions[target]

        mae = mean_absolute_error(
            actual,
            predictions
        )

        rmse = np.sqrt(
            mean_squared_error(
                actual,
                predictions
            )
        )

        r2 = r2_score(
            actual,
            predictions
        )

        advanced_results.append({
            "Target": target,
            "Model": model_name,
            "MAE": mae,
            "RMSE": rmse,
            "R2": r2
        })

advanced_results_df = pd.DataFrame(
    advanced_results
)

advanced_results_df

            Target              Model          MAE         RMSE        R2
0  EnrollmentCount      Random Forest    12.653750    13.539627 -0.384720
1    CourseRevenue      Random Forest  3085.796817  5258.587148  0.973673
2  EnrollmentCount  Gradient Boosting    13.815605    14.701413 -0.632550
3    CourseRevenue  Gradient Boosting  2763.735457  4082.276119  0.984134

## Display advanced-model metrics

In [22]:
formatted_advanced_results = (
    advanced_results_df.copy()
)

formatted_advanced_results["MAE"] = (
    formatted_advanced_results["MAE"].round(3)
)

formatted_advanced_results["RMSE"] = (
    formatted_advanced_results["RMSE"].round(3)
)

formatted_advanced_results["R2"] = (
    formatted_advanced_results["R2"].round(4)
)

formatted_advanced_results

            Target              Model       MAE      RMSE      R2
0  EnrollmentCount      Random Forest    12.654    13.540 -0.3847
1    CourseRevenue      Random Forest  3085.797  5258.587  0.9737
2  EnrollmentCount  Gradient Boosting    13.816    14.701 -0.6326
3    CourseRevenue  Gradient Boosting  2763.735  4082.276  0.9841

## Combine Day 10 and Day 11 results

In [23]:
all_model_results = pd.concat(
    [
        day10_metrics,
        advanced_results_df
    ],
    ignore_index=True
)

all_model_results

            Target              Model           MAE          RMSE        R2
0  EnrollmentCount      Mean Baseline     10.444444     11.774502 -0.047209
1    CourseRevenue      Mean Baseline  28413.556771  36217.344701 -0.248807
2  EnrollmentCount  Linear Regression     14.203758     19.812472 -1.965007
3    CourseRevenue  Linear Regression   2725.992334   3542.471175  0.988053
4  EnrollmentCount      Random Forest     12.653750     13.539627 -0.384720
5    CourseRevenue      Random Forest   3085.796817   5258.587148  0.973673
6  EnrollmentCount  Gradient Boosting     13.815605     14.701413 -0.632550
7    CourseRevenue  Gradient Boosting   2763.735457   4082.276119  0.984134

## Compare all models automatically

In [24]:
print("========== ALL MODEL COMPARISON ==========")

for target in target_columns:

    target_results = (
        all_model_results[
            all_model_results["Target"] == target
        ]
        .sort_values(by="MAE")
        .reset_index(drop=True)
    )

    print(f"\nTarget: {target}")
    print(target_results)

========== ALL MODEL COMPARISON ==========

Target: EnrollmentCount
            Target              Model        MAE       RMSE        R2
0  EnrollmentCount      Mean Baseline  10.444444  11.774502 -0.047209
1  EnrollmentCount      Random Forest  12.653750  13.539627 -0.384720
2  EnrollmentCount  Gradient Boosting  13.815605  14.701413 -0.632550
3  EnrollmentCount  Linear Regression  14.203758  19.812472 -1.965007

Target: CourseRevenue
          Target              Model           MAE          RMSE        R2
0  CourseRevenue  Linear Regression   2725.992334   3542.471175  0.988053
1  CourseRevenue  Gradient Boosting   2763.735457   4082.276119  0.984134
2  CourseRevenue      Random Forest   3085.796817   5258.587148  0.973673
3  CourseRevenue      Mean Baseline  28413.556771  36217.344701 -0.248807

## Identify the best model

In [25]:
best_models = []

for target in target_columns:

    target_results = all_model_results[
        all_model_results["Target"] == target
    ].copy()

    best_row = target_results.loc[
        target_results["MAE"].idxmin()
    ]

    best_models.append({
        "Target": target,
        "Best_Model": best_row["Model"],
        "MAE": best_row["MAE"],
        "RMSE": best_row["RMSE"],
        "R2": best_row["R2"]
    })

best_models_df = pd.DataFrame(best_models)

best_models_df

            Target         Best_Model          MAE         RMSE        R2
0  EnrollmentCount      Mean Baseline    10.444444    11.774502 -0.047209
1    CourseRevenue  Linear Regression  2725.992334  3542.471175  0.988053

## Create advanced prediction comparison

In [26]:
advanced_prediction_comparison = test_data[
    ["CourseID", "CourseName"]
].copy()

advanced_prediction_comparison[
    "Actual_EnrollmentCount"
] = y_test["EnrollmentCount"].values

advanced_prediction_comparison[
    "Random_Forest_EnrollmentCount"
] = rf_enrollment_predictions

advanced_prediction_comparison[
    "Gradient_Boosting_EnrollmentCount"
] = gb_enrollment_predictions

advanced_prediction_comparison[
    "Actual_CourseRevenue"
] = y_test["CourseRevenue"].values

advanced_prediction_comparison[
    "Random_Forest_CourseRevenue"
] = rf_revenue_predictions

advanced_prediction_comparison[
    "Gradient_Boosting_CourseRevenue"
] = gb_revenue_predictions

advanced_prediction_comparison

,CourseID,CourseName,Actual_EnrollmentCount,Random_Forest_EnrollmentCount,Gradient_Boosting_EnrollmentCount,Actual_CourseRevenue,Random_Forest_CourseRevenue,Gradient_Boosting_CourseRevenue
0,CR00050,Computer Vision,174,164.895,161.126480,85416.60,73410.2712,79770.165289
1,CR00036,Agile Project Management,177,160.420,159.814166,0.00,0.0000,91.232275
2,CR00049,Deep Learning,163,161.740,164.994517,67728.13,66359.7337,73135.921288
3,CR00002,Java Programming,149,162.655,164.795044,0.00,0.0000,91.232275
4,CR00055,Full-Stack Web Development,178,161.975,163.634997,10202.96,10192.7794,8923.857390
5,CR00034,Data Encryption,150,160.865,158.690263,59139.00,52664.5002,52489.733744
6,CR00035,Cyber Threat Intelligence,179,162.165,163.741628,0.00,0.0000,91.232275
7,CR00045,Financial Modeling,172,164.770,164.303930,0.00,0.0000,91.232275
8,CR00020,Email Marketing,155,169.805,172.814192,0.00,0.0000,91.232275
9,CR00048,AI Ethics,186,166.645,168.235969,0.00,223.0791,91.232275
10,CR00040,Leadership in Projects,174,158.900,158.226123,57070.26,48251.9770,50261.004369
11,CR00039,Project Planning,167,155.970,146.423466,57900.57,49771.7758,51074.988653

## Round prediction results

In [27]:
numeric_prediction_columns = [
    "Actual_EnrollmentCount",
    "Random_Forest_EnrollmentCount",
    "Gradient_Boosting_EnrollmentCount",
    "Actual_CourseRevenue",
    "Random_Forest_CourseRevenue",
    "Gradient_Boosting_CourseRevenue"
]

advanced_prediction_comparison = (
    advanced_prediction_comparison.round(
        {
            column: 2
            for column in numeric_prediction_columns
        }
    )
)

advanced_prediction_comparison

,CourseID,CourseName,Actual_EnrollmentCount,Random_Forest_EnrollmentCount,Gradient_Boosting_EnrollmentCount,Actual_CourseRevenue,Random_Forest_CourseRevenue,Gradient_Boosting_CourseRevenue
0,CR00050,Computer Vision,174,164.90,161.13,85416.60,73410.27,79770.17
1,CR00036,Agile Project Management,177,160.42,159.81,0.00,0.00,91.23
2,CR00049,Deep Learning,163,161.74,164.99,67728.13,66359.73,73135.92
3,CR00002,Java Programming,149,162.66,164.80,0.00,0.00,91.23
4,CR00055,Full-Stack Web Development,178,161.98,163.63,10202.96,10192.78,8923.86
5,CR00034,Data Encryption,150,160.86,158.69,59139.00,52664.50,52489.73
6,CR00035,Cyber Threat Intelligence,179,162.16,163.74,0.00,0.00,91.23
7,CR00045,Financial Modeling,172,164.77,164.30,0.00,0.00,91.23
8,CR00020,Email Marketing,155,169.80,172.81,0.00,0.00,91.23
9,CR00048,AI Ethics,186,166.64,168.24,0.00,223.08,91.23
10,CR00040,Leadership in Projects,174,158.90,158.23,57070.26,48251.98,50261.00
11,CR00039,Project Planning,167,155.97,146.42,57900.57,49771.78,51074.99

## Define Day 11 output path

In [28]:
model_folder = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data"
)

model_folder.mkdir(
    parents=True,
    exist_ok=True
)

day11_file_path = (
    model_folder /
    "EduPro_Day11_Advanced_Models.xlsx"
)

print("Day 11 output file:")
print(day11_file_path)

Day 11 output file:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day11_Advanced_Models.xlsx

## Saving Day 11 output

In [29]:
with pd.ExcelWriter(
    day11_file_path,
    engine="openpyxl"
) as writer:

    advanced_results_df.to_excel(
        writer,
        sheet_name="Advanced_Metrics",
        index=False
    )

    all_model_results.to_excel(
        writer,
        sheet_name="All_Model_Results",
        index=False
    )

    best_models_df.to_excel(
        writer,
        sheet_name="Best_Models",
        index=False
    )

    advanced_prediction_comparison.to_excel(
        writer,
        sheet_name="Predictions",
        index=False
    )

print("✅ Day 11 advanced model results saved successfully:")
print(day11_file_path)

✅ Day 11 advanced model results saved successfully:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day11_Advanced_Models.xlsx

## Reload and validate output

In [30]:
check_advanced_metrics = pd.read_excel(
    day11_file_path,
    sheet_name="Advanced_Metrics"
)

check_all_models = pd.read_excel(
    day11_file_path,
    sheet_name="All_Model_Results"
)

check_best_models = pd.read_excel(
    day11_file_path,
    sheet_name="Best_Models"
)

check_predictions = pd.read_excel(
    day11_file_path,
    sheet_name="Predictions"
)

print("========== DAY 11 OUTPUT VALIDATION ==========")

print("\nAdvanced metrics:")
print(check_advanced_metrics.shape)

print("\nAll model results:")
print(check_all_models.shape)

print("\nBest models:")
print(check_best_models.shape)

print("\nPredictions:")
print(check_predictions.shape)

print("\nOutput file exists:")
print(day11_file_path.exists())

========== DAY 11 OUTPUT VALIDATION ==========

Advanced metrics:
(4, 5)

All model results:
(8, 5)

Best models:
(2, 5)

Predictions:
(12, 8)

Output file exists:
True

## Final Day 11 validation

In [31]:
print("==============================================")
print("DAY 11 ADVANCED MODEL VALIDATION")
print("==============================================")

print("\nInput — Day 9:")
print(day9_file_path)

print("\nInput — Day 10:")
print(day10_file_path)

print("\nOutput — Day 11:")
print(day11_file_path)

print("\nTraining observations:")
print(len(X_train))

print("\nTesting observations:")
print(len(X_test))

print("\nNumber of features:")
print(len(feature_columns))

print("\nTargets:")
print(target_columns)

print("\nAdvanced models evaluated:")
print([
    "Random Forest",
    "Gradient Boosting"
])

print("\nDay 10 models retained for comparison:")
print([
    "Mean Baseline",
    "Linear Regression"
])

print("\nMetrics:")
print([
    "MAE",
    "RMSE",
    "R2"
])

print("\nOutput file exists:")
print(day11_file_path.exists())

print("\n==============================================")
print("DAY 11 COMPLETED")
print("==============================================")

==============================================
DAY 11 ADVANCED MODEL VALIDATION
==============================================

Input — Day 9:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day9_Train_Test_Splits.xlsx

Input — Day 10:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day10_Baseline_Models.xlsx

Output — Day 11:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\model_data\EduPro_Day11_Advanced_Models.xlsx

Training observations:
48

Testing observations:
12

Number of features:
9

Targets:
['EnrollmentCount', 'CourseRevenue']

Advanced models evaluated:
['Random Forest', 'Gradient Boosting']

Day 10 models retained for comparison:
['Mean Baseline', 'Linear Regression']

Metrics:
['MAE', 'RMSE', 'R2']

Output file exists:
True

==============================================
DAY 11 COMPLETED
==============================================