In [1]:
import pandas as pd
import numpy as np

In [2]:
cleaned_file_path = r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\cleaned_data\EduPro_Cleaned.xlsx"

In [3]:
users = pd.read_excel(
    cleaned_file_path,
    sheet_name="Users"
)

teachers = pd.read_excel(
    cleaned_file_path,
    sheet_name="Teachers"
)

courses = pd.read_excel(
    cleaned_file_path,
    sheet_name="Courses"
)

transactions = pd.read_excel(
    cleaned_file_path,
    sheet_name="Transactions"
)

## Checking data before merging

In [4]:
print("Users:", users.shape)
print("Teachers:", teachers.shape)
print("Courses:", courses.shape)
print("Transactions:", transactions.shape)

Users: (3000, 5)
Teachers: (60, 7)
Courses: (60, 8)
Transactions: (10000, 7)

## Checking key columns

In [5]:
print("Users columns:")
print(users.columns.tolist())

print("\nTeachers columns:")
print(teachers.columns.tolist())

print("\nCourses columns:")
print(courses.columns.tolist())

print("\nTransactions columns:")
print(transactions.columns.tolist())

Users columns:
['UserID', 'UserName', 'Age', 'Gender', 'Email']

Teachers columns:
['TeacherID', 'TeacherName', 'Age', 'Gender', 'Expertise', 'YearsOfExperience', 'TeacherRating']

Courses columns:
['CourseID', 'CourseName', 'CourseCategory', 'CourseType', 'CourseLevel', 'CoursePrice', 'CourseDuration', 'CourseRating']

Transactions columns:
['TransactionID', 'UserID', 'CourseID', 'TransactionDate', 'Amount', 'PaymentMethod', 'TeacherID']

In [6]:
users.columns

Index(['UserID', 'UserName', 'Age', 'Gender', 'Email'], dtype='str')

## Merging Transaction with Users

In [7]:
merged_data = transactions.merge(
    users,
    on="UserID",
    how="left"
)

In [8]:
print(merged_data.shape)

(10000, 11)

## Checking first merge

In [9]:
merged_data.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,UserName,Age,Gender,Email
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040,morrisonamanda,33,Female,ganderson@yahoo.com
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040,morrisonamanda,33,Female,ganderson@yahoo.com
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040,morrisonamanda,33,Female,ganderson@yahoo.com
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040,fthornton,23,Female,christensencatherine@outlook.com
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042,fthornton,23,Female,christensencatherine@outlook.com

## Verify the first merge

In [10]:
print("Rows after Users merge:", len(merged_data))

Rows after Users merge: 10000

In [11]:
print(merged_data["UserName"].isnull().sum())

0

## Merging with Courses

In [12]:
merged_data = merged_data.merge(
    courses,
    on="CourseID",
    how="left"
)

In [13]:
print(merged_data.shape)

(10000, 18)

In [14]:
merged_data.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,UserName,Age,Gender,Email,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040,morrisonamanda,33,Female,ganderson@yahoo.com,Digital Marketing,Marketing,Free,Intermediate,0.0,42.68,4.72
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040,morrisonamanda,33,Female,ganderson@yahoo.com,Scrum Essentials,Project Management,Free,Intermediate,0.0,33.93,3.45
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040,morrisonamanda,33,Female,ganderson@yahoo.com,Content Marketing,Marketing,Free,Advanced,0.0,18.00,2.98
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040,fthornton,23,Female,christensencatherine@outlook.com,AI Ethics,Artificial Intelligence,Free,Beginner,0.0,42.70,3.64
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042,fthornton,23,Female,christensencatherine@outlook.com,Content Creation,Digital Marketing,Free,Beginner,0.0,8.95,2.14

## Verify the Course merge

In [15]:

print("Rows after Courses merge:", len(merged_data))

Rows after Courses merge: 10000

In [16]:
print("Missing CourseName:",
      merged_data["CourseName"].isnull().sum())

Missing CourseName: 0

## Merging with Teachers

In [17]:
merged_data = merged_data.merge(
    teachers,
    on="TeacherID",
    how="left"
)

In [18]:
print(merged_data.shape)

(10000, 24)

In [19]:
merged_data.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,UserName,Age_x,Gender_x,...,CourseLevel,CoursePrice,CourseDuration,CourseRating,TeacherName,Age_y,Gender_y,Expertise,YearsOfExperience,TeacherRating
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040,morrisonamanda,33,Female,...,Intermediate,0.0,42.68,4.72,Kimberly Miller,49,Male,Cybersecurity,24,4.58
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040,morrisonamanda,33,Female,...,Intermediate,0.0,33.93,3.45,Kimberly Miller,49,Male,Cybersecurity,24,4.58
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040,morrisonamanda,33,Female,...,Advanced,0.0,18.00,2.98,Kimberly Miller,49,Male,Cybersecurity,24,4.58
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040,fthornton,23,Female,...,Beginner,0.0,42.70,3.64,Kimberly Miller,49,Male,Cybersecurity,24,4.58
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042,fthornton,23,Female,...,Beginner,0.0,8.95,2.14,Yolanda Levine,49,Female,Machine Learning,21,4.97

## Verify the final merge

In [20]:
print("Final rows:", len(merged_data))
print("Final columns:", len(merged_data.columns))

Final rows: 10000
Final columns: 24

## Checking final columns

In [21]:
print(merged_data.columns.tolist())

['TransactionID', 'UserID', 'CourseID', 'TransactionDate', 'Amount', 'PaymentMethod', 'TeacherID', 'UserName', 'Age_x', 'Gender_x', 'Email', 'CourseName', 'CourseCategory', 'CourseType', 'CourseLevel', 'CoursePrice', 'CourseDuration', 'CourseRating', 'TeacherName', 'Age_y', 'Gender_y', 'Expertise', 'YearsOfExperience', 'TeacherRating']

## Handling duplicates columns names

In [22]:
merged_data = merged_data.rename(columns={
    "Age_x": "UserAge",
    "Gender_x": "UserGender",
    "Age_y": "TeacherAge",
    "Gender_y": "TeacherGender"
})

## Check the final data types

In [23]:
print(merged_data.dtypes)

TransactionID                   str
UserID                          str
CourseID                        str
TransactionDate      datetime64[us]
Amount                      float64
PaymentMethod                   str
TeacherID                       str
UserName                        str
UserAge                       int64
UserGender                      str
Email                           str
CourseName                      str
CourseCategory                  str
CourseType                      str
CourseLevel                     str
CoursePrice                 float64
CourseDuration              float64
CourseRating                float64
TeacherName                     str
TeacherAge                    int64
TeacherGender                   str
Expertise                       str
YearsOfExperience             int64
TeacherRating               float64
dtype: object

## Check missing values after merging

In [24]:
merged_data.isnull().sum()

TransactionID        0
UserID               0
CourseID             0
TransactionDate      0
Amount               0
PaymentMethod        0
TeacherID            0
UserName             0
UserAge              0
UserGender           0
Email                0
CourseName           0
CourseCategory       0
CourseType           0
CourseLevel          0
CoursePrice          0
CourseDuration       0
CourseRating         0
TeacherName          0
TeacherAge           0
TeacherGender        0
Expertise            0
YearsOfExperience    0
TeacherRating        0
dtype: int64

In [25]:
print("Total missing values:",
      merged_data.isnull().sum().sum())

Total missing values: 0

## Check Duplicates

In [26]:
print("Duplicate rows:",
      merged_data.duplicated().sum())

Duplicate rows: 0

In [27]:
print("Duplicate TransactionIDs:",
      merged_data["TransactionID"].duplicated().sum())

Duplicate TransactionIDs: 0

## Final Dataset Inspection

In [28]:
merged_data.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,UserName,UserAge,UserGender,...,CourseLevel,CoursePrice,CourseDuration,CourseRating,TeacherName,TeacherAge,TeacherGender,Expertise,YearsOfExperience,TeacherRating
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040,morrisonamanda,33,Female,...,Intermediate,0.0,42.68,4.72,Kimberly Miller,49,Male,Cybersecurity,24,4.58
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040,morrisonamanda,33,Female,...,Intermediate,0.0,33.93,3.45,Kimberly Miller,49,Male,Cybersecurity,24,4.58
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040,morrisonamanda,33,Female,...,Advanced,0.0,18.00,2.98,Kimberly Miller,49,Male,Cybersecurity,24,4.58
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040,fthornton,23,Female,...,Beginner,0.0,42.70,3.64,Kimberly Miller,49,Male,Cybersecurity,24,4.58
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042,fthornton,23,Female,...,Beginner,0.0,8.95,2.14,Yolanda Levine,49,Female,Machine Learning,21,4.97

In [29]:
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TransactionID      10000 non-null  str
 1   UserID             10000 non-null  str
 2   CourseID           10000 non-null  str
 3   TransactionDate    10000 non-null  datetime64[us]
 4   Amount             10000 non-null  float64
 5   PaymentMethod      10000 non-null  str
 6   TeacherID          10000 non-null  str
 7   UserName           10000 non-null  str
 8   UserAge            10000 non-null  int64
 9   UserGender         10000 non-null  str
 10  Email              10000 non-null  str
 11  CourseName         10000 non-null  str
 12  CourseCategory     10000 non-null  str
 13  CourseType         10000 non-null  str
 14  CourseLevel        10000 non-null  str
 15  CoursePrice        10000 non-null  float64
 16  CourseDuration     10000 non-null  float64
 17  CourseRating       10000 non-null  float64
 18  TeacherName        10000 non-null  str
 19  TeacherAge         10000 non-null  int64
 20  TeacherGender      10000 non-null  str
 21  Expertise          10000 non-null  str
 22  YearsOfExperience  10000 non-null  int64
 23  TeacherRating      10000 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(3), str(15)
memory usage: 3.3 MB

In [30]:
merged_data.describe()

,TransactionDate,Amount,UserAge,CoursePrice,CourseDuration,CourseRating,TeacherAge,YearsOfExperience,TeacherRating
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-07-01 03:50:32.640000,91.132347,24.965700,91.132347,27.509536,3.123277,44.885000,16.024100,4.087769
min,2025-01-01 00:00:00,0.000000,15.000000,0.000000,1.200000,1.130000,27.000000,1.000000,1.050000
25%,2025-04-02 00:00:00,0.000000,20.000000,0.000000,12.130000,2.140000,44.000000,7.000000,3.460000
50%,2025-06-30 00:00:00,0.000000,25.000000,0.000000,28.330000,3.110000,49.000000,21.000000,4.580000
75%,2025-09-28 00:00:00,119.040000,30.000000,119.040000,42.700000,4.110000,49.000000,24.000000,4.970000
max,2025-12-30 00:00:00,490.900000,35.000000,490.900000,49.730000,4.940000,50.000000,24.000000,4.970000
std,NaN,152.063524,6.051858,152.063524,16.011616,1.156254,6.988566,8.521783,1.069542

In [31]:
merged_data["CourseCategory"].value_counts()

CourseCategory
Data Science               916
Finance                    864
Web Development            844
Business                   833
Project Management         829
Artificial Intelligence    829
Design                     827
Cybersecurity              819
Machine Learning           819
Digital Marketing          808
Marketing                  806
Programming                806
Name: count, dtype: int64

In [32]:
merged_data["PaymentMethod"].value_counts()

PaymentMethod
PayPal           3389
Credit Card      3333
Bank Transfer    3278
Name: count, dtype: int64

## Important predictive-modeling preparation

In [33]:
merged_data["TransactionYear"] = merged_data["TransactionDate"].dt.year
merged_data["TransactionMonth"] = merged_data["TransactionDate"].dt.month
merged_data["TransactionDay"] = merged_data["TransactionDate"].dt.day
merged_data["TransactionDayOfWeek"] = merged_data["TransactionDate"].dt.dayofweek

In [34]:
merged_data["TransactionQuarter"] = merged_data["TransactionDate"].dt.quarter

## Check the new featuers

In [35]:
merged_data[
    [
        "TransactionDate",
        "TransactionYear",
        "TransactionMonth",
        "TransactionDay",
        "TransactionDayOfWeek",
        "TransactionQuarter"
    ]
].head()

,TransactionDate,TransactionYear,TransactionMonth,TransactionDay,TransactionDayOfWeek,TransactionQuarter
0,2025-10-25,2025,10,25,5,4
1,2025-01-13,2025,1,13,0,1
2,2025-03-28,2025,3,28,4,1
3,2025-06-02,2025,6,2,0,2
4,2025-08-10,2025,8,10,6,3

## Saving working

In [36]:
from pathlib import Path

prepared_folder = Path(
    r"D:\Data Analytics Project\EduPro_Predictive_Modeling\data\prepared_data"
)

prepared_folder.mkdir(parents=True, exist_ok=True)

prepared_file_path = prepared_folder / "EduPro_Prepared.xlsx"

In [37]:
merged_data.to_excel(
    prepared_file_path,
    sheet_name="Prepared_Data",
    index=False
)

print(f"Prepared dataset saved at:\n{prepared_file_path}")

Prepared dataset saved at:
D:\Data Analytics Project\EduPro_Predictive_Modeling\data\prepared_data\EduPro_Prepared.xlsx

## Reload and verify the saved files

In [38]:
prepared_check = pd.read_excel(
    prepared_file_path,
    sheet_name="Prepared_Data"
)

In [39]:
print(prepared_check.shape)

(10000, 29)

In [40]:
print(prepared_check.head())

  TransactionID  UserID CourseID TransactionDate  Amount  PaymentMethod  \
0       TT00001  U00003  CR00016      2025-10-25     0.0         PayPal
1       TT00002  U00003  CR00037      2025-01-13     0.0         PayPal
2       TT00003  U00003  CR00019      2025-03-28     0.0  Bank Transfer
3       TT00004  U00004  CR00048      2025-06-02     0.0  Bank Transfer
4       TT00005  U00004  CR00060      2025-08-10     0.0         PayPal

  TeacherID        UserName  UserAge UserGender  ... TeacherAge TeacherGender  \
0   TC00040  morrisonamanda       33     Female  ...         49          Male
1   TC00040  morrisonamanda       33     Female  ...         49          Male
2   TC00040  morrisonamanda       33     Female  ...         49          Male
3   TC00040       fthornton       23     Female  ...         49          Male
4   TC00042       fthornton       23     Female  ...         49        Female

          Expertise YearsOfExperience TeacherRating  TransactionYear  \
0     Cybersecurity                24          4.58             2025
1     Cybersecurity                24          4.58             2025
2     Cybersecurity                24          4.58             2025
3     Cybersecurity                24          4.58             2025
4  Machine Learning                21          4.97             2025

   TransactionMonth  TransactionDay TransactionDayOfWeek  TransactionQuarter
0                10              25                    5                   4
1                 1              13                    0                   1
2                 3              28                    4                   1
3                 6               2                    0                   2
4                 8              10                    6                   3

[5 rows x 29 columns]

## Final Validation

In [41]:
print("FINAL DAY 3 VALIDATION")
print("----------------------")

print("Rows:", merged_data.shape[0])
print("Columns:", merged_data.shape[1])
print("Missing Values:", merged_data.isnull().sum().sum())
print("Duplicate Rows:", merged_data.duplicated().sum())
print("Duplicate TransactionIDs:",
      merged_data["TransactionID"].duplicated().sum())

FINAL DAY 3 VALIDATION
----------------------
Rows: 10000
Columns: 29
Missing Values: 0
Duplicate Rows: 0
Duplicate TransactionIDs: 0